drivers: char: remove unused var 'req_complete'
../../../../../../kernel/razer/sdm845/drivers/char/adsprpc.c:3939:25: error: unused variable 'req_complete' [-Werror,-Wunused-variable]